export const types = {
  // get contracts List
  GET_CONTRACTS_REQUEST: "GET_CONTRACTS_REQUEST",
  GET_CONTRACTS_SUCCESS: "GET_CONTRACTS_SUCCESS",
  GET_CONTRACTS_FAILURE: "GET_CONTRACTS_FAILURE",

  // get contracts List
  SIGN_CONTRACT_REQUEST: "SIGN_CONTRACT_REQUEST",
  SIGN_CONTRACT_SUCCESS: "SIGN_CONTRACT_SUCCESS",
  SIGN_CONTRACT_FAILURE: "SIGN_CONTRACT_FAILURE",
};
