export const types = {
  // get employees List
  GET_EMPLOYEES_REQUEST: "GET_EMPLOYEES_REQUEST",
  GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
  GET_EMPLOYEES_FAILURE: "GET_EMPLOYEES_FAILURE",

  // get employee time sheet
  GET_EMPLOYEE_TIMESHEET_REQUEST: "GET_EMPLOYEE_TIMESHEET_REQUEST",
  GET_EMPLOYEE_TIMESHEET_SUCCESS: "GET_EMPLOYEE_TIMESHEET_SUCCESS",
  GET_EMPLOYEE_TIMESHEET_FAILURE: "GET_EMPLOYEE_TIMESHEET_FAILURE",

  // update employee time sheet
  UPDATE_EMPLOYEE_TIMESHEET_REQUEST: "UPDATE_EMPLOYEE_TIMESHEET_REQUEST",
  UPDATE_EMPLOYEE_TIMESHEET_SUCCESS: "UPDATE_EMPLOYEE_TIMESHEET_SUCCESS",
  UPDATE_EMPLOYEE_TIMESHEET_FAILURE: "UPDATE_EMPLOYEE_TIMESHEET_FAILURE",

  // get single employee
  GET_EMPLOYEE_REQUEST: "GET_EMPLOYEE_REQUEST",
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
  GET_EMPLOYEE_FAILURE: "GET_EMPLOYEE_FAILURE",

  // get single employee
  EDIT_EMPLOYEE_REQUEST: "EDIT_EMPLOYEE_REQUEST",
  EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
  EDIT_EMPLOYEE_FAILURE: "EDIT_EMPLOYEE_FAILURE",

  // get activities List
  GET_ACTIVITIES_REQUEST: "GET_ACTIVITIES_REQUEST",
  GET_ACTIVITIES_SUCCESS: "GET_ACTIVITIES_SUCCESS",
  GET_ACTIVITIES_FAILURE: "GET_ACTIVITIES_FAILURE",

  // change employee status
  CHANGE_EMPLOYEE_STATUS_REQUEST: "CHANGE_EMPLOYEE_STATUS_REQUEST",
  CHANGE_EMPLOYEE_STATUS_SUCCESS: "CHANGE_EMPLOYEE_STATUS_SUCCESS",
  CHANGE_EMPLOYEE_STATUS_FAILURE: "CHANGE_EMPLOYEE_STATUS_FAILURE",

  // delete employee
  DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_FAILURE: "DELETE_EMPLOYEE_FAILURE",

  // add employee
  ADD_EMPLOYEE_REQUEST: "ADD_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAILURE: "ADD_EMPLOYEE_FAILURE",

  // add vendor signature
  ADD_SIGNATURE_REQUEST: "ADD_SIGNATURE_REQUEST",
  ADD_SIGNATURE_SUCCESS: "ADD_SIGNATURE_SUCCESS",
  ADD_SIGNATURE_FAILURE: "ADD_SIGNATURE_FAILURE",

  // upload vendor signature
  UPLOAD_VENDOR_SIGNATURE_REQUEST: "UPLOAD_VENDOR_SIGNATURE_REQUEST",
  UPLOAD_VENDOR_SIGNATURE_SUCCESS: "UPLOAD_VENDOR_SIGNATURE_SUCCESS",
  UPLOAD_VENDOR_SIGNATURE_FAILURE: "UPLOAD_VENDOR_SIGNATURE_FAILURE",

  // upload emplopyee signature
  UPLOAD_EMPLOYEE_SIGNATURE_REQUEST: "UPLOAD_EMPLOYEE_SIGNATURE_REQUEST",
  UPLOAD_EMPLOYEE_SIGNATURE_SUCCESS: "UPLOAD_EMPLOYEE_SIGNATURE_SUCCESS",
  UPLOAD_EMPLOYEE_SIGNATURE_FAILURE: "UPLOAD_EMPLOYEE_SIGNATURE_FAILURE",

  // update time sheet status
  UPDATE_TIMESHEET_STATUS_REQUEST: "UPDATE_TIMESHEET_STATUS_REQUEST",
  UPDATE_TIMESHEET_STATUS_SUCCESS: "UPDATE_TIMESHEET_STATUS_SUCCESS",
  UPDATE_TIMESHEET_STATUS_FAILURE: "UPDATE_TIMESHEET_STATUS_FAILURE",
  // update milage
  UPDATE_MILAGE_REQUEST: "UPDATE_MILAGE_REQUEST",
  UPDATE_MILAGE_SUCCESS: "UPDATE_MILAGE_SUCCESS",
  UPDATE_MILAGE_FAILURE: "UPDATE_MILAGE_FAILURE",
};
