const types = {
  // get inventory List
  GET_INVENTORY_REQUEST: "GET_INVENTORY_REQUEST",
  GET_INVENTORY_SUCCESS: "GET_INVENTORY_SUCCESS",
  GET_INVENTORY_FAILURE: "GET_INVENTORY_FAILURE",

    // get single inventory 
    GET_SINGLE_INVENTORY_REQUEST: "GET_SINGLE_INVENTORY_REQUEST",
    GET_SINGLE_INVENTORY_SUCCESS: "GET_SINGLE_INVENTORY_SUCCESS",
    GET_SINGLE_INVENTORY_FAILURE: "GET_SINGLE_INVENTORY_FAILURE",

  // get inventory group list
  GET_INVENTORY_GROUP_REQUEST: "GET_INVENTORY_GROUP_REQUEST",
  GET_INVENTORY_GROUP_SUCCESS: "GET_INVENTORY_GROUP_SUCCESS",
  GET_INVENTORY_GROUP_FAILURE: "GET_INVENTORY_GROUP_FAILURE",

  // get inventory category list
  GET_INVENTORY_CATEGORIES_REQUEST: "GET_INVENTORY_CATEGORIES_REQUEST",
  GET_INVENTORY_CATEGORIES_SUCCESS: "GET_INVENTORY_CATEGORIES_SUCCESS",
  GET_INVENTORY_CATEGORIES_FAILURE: "GET_INVENTORY_CATEGORIES_FAILURE",

  // get inventory category list
  GET_ATTRIBUTES_REQUEST: "GET_ATTRIBUTES_REQUEST",
  GET_ATTRIBUTES_SUCCESS: "GET_ATTRIBUTES_SUCCESS",
  GET_ATTRIBUTES_FAILURE: "GET_ATTRIBUTES_FAILURE",

  // add attachments
  ADD_ATTACHMENTS_REQUEST: "ADD_ATTACHMENTS_REQUEST",
  ADD_ATTACHMENTS_SUCCESS: "ADD_ATTACHMENTS_SUCCESS",
  ADD_ATTACHMENTS_FAILURE: "ADD_ATTACHMENTS_FAILURE",

  // add Inventory
  ADD_INVENTORY_REQUEST: "ADD_INVENTORY_REQUEST",
  ADD_INVENTORY_SUCCESS: "ADD_INVENTORY_SUCCESS",
  ADD_INVENTORY_FAILURE: "ADD_INVENTORY_FAILURE",

   // add Inventory
   EDIT_INVENTORY_REQUEST: "EDIT_INVENTORY_REQUEST",
   EDIT_INVENTORY_SUCCESS: "EDIT_INVENTORY_SUCCESS",
   EDIT_INVENTORY_FAILURE: "EDIT_INVENTORY_FAILURE",

  // delete inventory
  DELETE_INVENTORY_REQUEST: "DELETE_INVENTORY_REQUEST",
  DELETE_INVENTORY_SUCCESS: "DELETE_INVENTORY_SUCCESS",
  DELETE_INVENTORY_FAILURE: "DELETE_INVENTORY_FAILURE",
};
export default types;
