export const types = {
  // get order List
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",

  // get order List
  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
  GET_ORDER_DETAIL_FAILURE: "GET_ORDER_DETAIL_FAILURE",

  // get order List
  GET_ORDER_STATUS_LIST_REQUEST: "GET_ORDER_STATUS_LIST_REQUEST",
  GET_ORDER_STATUS_LIST_SUCCESS: "GET_ORDER_STATUS_LIST_SUCCESS",
  GET_ORDER_STATUS_LIST_FAILURE: "GET_ORDER_STATUS_LIST_FAILURE",

  // update order status
  UPDATE_ORDER_STATUS_REQUEST: "UPDATE_ORDER_STATUS_REQUEST",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAILURE: "UPDATE_ORDER_STATUS_FAILURE",
};
