export const supplierUrl = 'https://gonjesupplier.vercel.app/'
export const vendorUrl = 'https://gonjevendors.vercel.app/'
// export const customerUrl = '/'
export const customerUrl = 'https://gonjecustomer.vercel.app/'
export const superadminUrl = 'https://gonje-superadmin.vercel.app/'
