export const RETRIEVE_USER = "RETRIEVE_USER";

export const DELIVERY_DATE = "DELIVERY_DATE";

export const RETRIEVE_CATEGORY = "RETRIEVE_CATEGORY";

export const ORDER_LISTING = "ORDER_LISTING";

export const PRODUCT_RETRIEVE = "PRODUCT_RETRIEVE";

export const GETTING_CART_COUNT = "GETTING_CART_COUNT";

export const SET_CLASSNAME = "SET_CLASSNAME";

export const SET_SHOPID = "SET_SHOPID";

export const SET_USER_DETAIL = "SET_USER_DETAIL";

export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";

export const LISTING_CART_PRODUCT = "LISTING_CART_PRODUCT";

export const SET_PAGENAME = "SET_PAGENAME";

export const ADDRESS_DETAIL = "ADDRESS_DETAIL";

export const RECIPE_LISTING = "RECIPE_LISTING";

export const RECIPE_DETAIL = "RECIPE_DETAIL";
export const LISTING_NOTIFICATIONS = "LISTING_NOTIFICATIONS";
export const UPDATE_NOTIFICATIONS_STATUS = "UPDATE_NOTIFICATIONS_STATUS";
